# Generated by Django 4.2.11 on 2024-08-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0028_alter_loainguoidung_managers_loainguoidung_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Loai_NguoiDung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BanVe.loainguoidung'),
        ),
    ]
