# Generated by Django 4.2.11 on 2024-09-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BanVe', '0030_khachhang_user_nhanvien_user_taixe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
